name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - name: Run lint and tests
        run: |
          npm ci
          npm run lint
          npm run test
        
      - name: Create release branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout -b releases/${{ github.run_number }}
          git push origin releases/${{ github.run_number }}
        
      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/${{ secrets.crpj0rsfvvem9ps4apgr }}/app:${{ github.run_number }} .
          docker tag cr.yandex/${{ secrets.crpj0rsfvvem9ps4apgr }}/app:${{ github.run_number }} cr.yandex/${{ secrets.Rcrpj0rsfvvem9ps4apgr }}/app:latest
          docker push cr.yandex/${{ secrets.crpj0rsfvvem9ps4apgr }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.crpj0rsfvvem9ps4apgr }}/app:latest
        
      - name: Create tag
        run: |
          git tag v${{ github.run_number }}
          git push origin v${{ github.run_number }}
        
      - name: Create release issue
        run: |
          gh issue create --title "Release v${{ github.run_number }}" --body "Release details..."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}